name: fourmolu
on:
  - push
  - pullrequest
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.14.0.0"
